### ISSUE TITLE
order of menu items according to the position of the addon icon

### ISSUE THREAD

**Issue by efbe** [Ajnasz/grwatcher#5]
ola!

It would be awsome if the dropdown list menu items order will follow the position of the addon icon and according to that:
- if the icon is in the upper part - the item order would be: (from the top) 'check for unread feeds', 'preferences', 'open google reader', 'mark all as read' + the feed names
- if the icon is at the bottom - use the actual layout (service menu items on the bottom starting with 'check for unread feeds' from the bottom to the top... feed names above them)

cheers,

eFBe

**Comment by Ajnasz** [comment]
Issue fixed, will be available soon.
thanks
